builders:
  build_metadata:
    import: "package:build_metadata/builder.dart"
    builder_factories:
      - "buildMetadata"
    build_extensions: 
      $lib$:
        - "build_metadata.dart"
    build_to: source
    auto_apply: dependents
